---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sabnzbd-scripts
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-sabnzbd-scripts
  storageClassName: nfs-csi
